# Generated by Django 5.2.7 on 2025-10-24 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encryptor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filemetadata',
            name='category',
            field=models.CharField(default='Others', max_length=20),
        ),
    ]
