# Generated by Django 5.2.7 on 2025-11-21 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_user_failed_login_attempts_user_is_locked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subscription_plan',
            field=models.CharField(choices=[('FREE', 'Free Tier'), ('STANDARD', 'Standard Tier'), ('PRO', 'Pro Tier')], default='FREE', help_text='Current Subscription Tier', max_length=10),
        ),
    ]
