# Generated by Django 5.2.7 on 2025-12-05 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_user_subscription_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='recovery_encrypted_dek',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_locked',
            field=models.BooleanField(default=False, help_text='If true, the user is locked out.'),
        ),
    ]
