# Generated by Django 5.2.7 on 2025-12-08 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0004_user_recovery_encrypted_dek_alter_user_is_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subscription_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='upload_limit_mb',
            field=models.IntegerField(default=500, help_text='Max upload size in MB'),
        ),
    ]
